GRANT SELECT_PRIV ON *.*.* TO 'jack'@'%';
GRANT SELECT_PRIV, ALTER_PRIV, LOAD_PRIV ON ctl1.db1.tbl1 TO 'jack'@'192.8.%';
GRANT LOAD_PRIV ON ctl1.db1.* TO ROLE 'my_role';
GRANT USAGE_PRIV ON RESOURCE * TO 'jack'@'%';
GRANT USAGE_PRIV ON RESOURCE 'spark_resource' TO 'jack'@'%';
GRANT USAGE_PRIV ON RESOURCE 'spark_resource' TO ROLE 'my_role';
GRANT 'role1', 'role2' TO 'jack'@'%';
GRANT USAGE_PRIV ON WORKLOAD GROUP 'g1' TO 'jack'@'%';
GRANT USAGE_PRIV ON WORKLOAD GROUP '%' TO 'jack'@'%';
GRANT USAGE_PRIV ON WORKLOAD GROUP 'g1' TO ROLE 'my_role';
GRANT SHOW_VIEW_PRIV ON db1.view1 TO 'jack'@'%';
GRANT USAGE_PRIV ON COMPUTE GROUP 'group1' TO 'jack'@'%';
GRANT USAGE_PRIV ON COMPUTE GROUP 'group1' TO ROLE 'my_role';
GRANT USAGE_PRIV ON COMPUTE GROUP '*' TO 'jack'@'%';
GRANT USAGE_PRIV ON STORAGE VAULT 'vault1' TO 'jack'@'%';
GRANT USAGE_PRIV ON STORAGE VAULT 'vault1' TO ROLE 'my_role';
GRANT USAGE_PRIV ON STORAGE VAULT '*' TO 'jack'@'%'
