ALTER USER jack@'%' IDENTIFIED BY "12345";
ALTER USER jack@'%' FAILED_LOGIN_ATTEMPTS 3 PASSWORD_LOCK_TIME 1 DAY;
ALTER USER jack@'%' ACCOUNT_UNLOCK;
ALTER USER jack@'%' COMMENT "this is my first user"
