CREATE TABLE t1(c1 INT, c2 STRING)
DUPLICATE KEY(c1)
DISTRIBUTED BY HASH(c1)
PROPERTIES('replication_num' = '1');

CREATE TABLE t2(c1 INT, c2 INT MAX)
AGGREGATE KEY(c1)
DISTRIBUTED BY HASH(c1)
PROPERTIES('replication_num' = '1');

CREATE TABLE t3(c1 INT, c2 INT)
UNIQUE KEY(c1)
DISTRIBUTED BY HASH(c1)
PROPERTIES('replication_num' = '1');

CREATE TABLE t5(c1 INT, c2 INT DEFAULT 10)
DUPLICATE KEY(c1)
DISTRIBUTED BY HASH(c1)
PROPERTIES('replication_num' = '1');

CREATE TABLE t6(c1 INT, c2 INT)
DUPLICATE KEY(c1)
DISTRIBUTED BY RANDOM
PROPERTIES('replication_num' = '1');

CREATE TABLE example_db.table_hash(k1 BIGINT, k2 LARGEINT, v1 VARCHAR(2048), v2 SMALLINT DEFAULT "10")
UNIQUE KEY(k1, k2)
DISTRIBUTED BY HASH(k1, k2) BUCKETS 32
PROPERTIES("storage_medium" = "SSD", "storage_cooldown_time" = "2015-06-04 00:00:00");

CREATE TABLE t10
PROPERTIES('replication_num' = '1')
AS SELECT * FROM t1;

CREATE TABLE t11 LIKE t10
