CREATE TABLE t1(c1 INT, c2 STRING) DUPLICATE KEY(c1) DISTRIBUTED BY HASH(c1) PROPERTIES ('replication_num' = '1');
CREATE TABLE t2(c1 INT, c2 INT MAX) AGGREGATE KEY(c1) DISTRIBUTED BY HASH(c1) PROPERTIES ('replication_num' = '1');
CREATE TABLE t3(c1 INT, c2 INT) UNIQUE KEY(c1) DISTRIBUTED BY HASH(c1) PROPERTIES ('replication_num' = '1');
CREATE TABLE t4(c1 INT, c2 INT GENERATED ALWAYS AS (c1 + 1)) DUPLICATE KEY(c1) DISTRIBUTED BY HASH(c1) PROPERTIES ('replication_num' = '1');
CREATE TABLE t5(c1 INT, c2 INT DEFAULT 10) DUPLICATE KEY(c1) DISTRIBUTED BY HASH(c1) PROPERTIES ('replication_num' = '1');
CREATE TABLE t6(c1 INT, c2 INT) DUPLICATE KEY(c1) DISTRIBUTED BY RANDOM PROPERTIES ('replication_num' = '1');
CREATE TABLE t7(c1 INT, c2 DATETIME NOT NULL) DUPLICATE KEY(c1) AUTO PARTITION BY RANGE(date_trunc(c2, 'day')) () DISTRIBUTED BY RANDOM PROPERTIES ('replication_num' = '1');
CREATE TABLE t8(c1 INT, c2 DATETIME NOT NULL) DUPLICATE KEY(c1) PARTITION BY RANGE(c2) (FROM ('2020-01-01') TO ('2020-01-10') INTERVAL 1 DAY) DISTRIBUTED BY RANDOM PROPERTIES ('replication_num' = '1');
CREATE TABLE t9(c1 INT, c2 DATE NOT NULL) DUPLICATE KEY(c1) PARTITION BY LIST(c2) (PARTITION p1 VALUES IN (('2020-01-01'), ('2020-01-02'))) DISTRIBUTED BY RANDOM PROPERTIES ('replication_num' = '1');
CREATE TABLE example_db.table_hash(k1 BIGINT, k2 LARGEINT, v1 VARCHAR(2048), v2 SMALLINT DEFAULT "10") UNIQUE KEY(k1, k2) DISTRIBUTED BY HASH(k1, k2) BUCKETS 32 PROPERTIES("storage_medium" = "SSD", "storage_cooldown_time" = "2015-06-04 00:00:00");
CREATE TABLE IF NOT EXISTS create_table_use_created_policy (k1 BIGINT, k2 LARGEINT, v1 VARCHAR(2048)) UNIQUE KEY(k1) DISTRIBUTED BY HASH(k1) BUCKETS 3 PROPERTIES("storage_policy" = "test_create_table_use_policy", "replication_num" = "1");
CREATE TABLE t1 (id INT COMMENT "", value VARCHAR(8) COMMENT "") DUPLICATE KEY(id) DISTRIBUTED BY HASH(id) BUCKETS 10 PROPERTIES ("colocate_with" = "group1");
CREATE TABLE t2 (id INT COMMENT "", value1 VARCHAR(8) COMMENT "", value2 VARCHAR(8) COMMENT "") DUPLICATE KEY(id) DISTRIBUTED BY HASH(id) BUCKETS 10 PROPERTIES ("colocate_with" = "group1");
CREATE TABLE example_db.table_hash(k1 TINYINT, k2 DECIMAL(10, 2) DEFAULT "10.5", v1 CHAR(10) REPLACE, v2 INT SUM, INDEX k1_idx (k1) USING INVERTED COMMENT 'my first index') AGGREGATE KEY(k1, k2) DISTRIBUTED BY HASH(k1) BUCKETS 32 PROPERTIES ("bloom_filter_columns" = "k2");
CREATE TABLE example_db.table_hash(k1 TINYINT, k2 DECIMAL(10, 2) DEFAULT "10.5") DISTRIBUTED BY HASH(k1) BUCKETS 32 PROPERTIES ("replication_allocation" = "tag.location.group_a:1, tag.location.group_b:2");
CREATE TABLE example_db.dynamic_partition(k1 DATE, k2 INT, k3 SMALLINT, v1 VARCHAR(2048), v2 DATETIME DEFAULT "2014-02-04 15:36:00") DUPLICATE KEY(k1, k2, k3) PARTITION BY RANGE(k1) () DISTRIBUTED BY HASH(k2) BUCKETS 32 PROPERTIES("dynamic_partition.time_unit" = "DAY", "dynamic_partition.start" = "-3", "dynamic_partition.end" = "3", "dynamic_partition.prefix" = "p", "dynamic_partition.buckets" = "32");
CREATE TABLE t10 PROPERTIES ('replication_num' = '1') AS SELECT * FROM t1;
CREATE TABLE t11 LIKE t10
