INSERT INTO test VALUES (1, 2);
INSERT INTO test (c1, c2) VALUES (1, 2);
INSERT INTO test (c1, c2) VALUES (1, DEFAULT);
INSERT INTO test (c1) VALUES (1);
INSERT INTO test VALUES (1, 2), (3, 2 + 2);
INSERT INTO test (c1, c2) VALUES (1, 2), (3, 2 * 2);
INSERT INTO test (c1) VALUES (1), (3);
INSERT INTO test (c1, c2) VALUES (1, DEFAULT), (3, DEFAULT);
INSERT INTO test SELECT * FROM test2;
INSERT INTO test (c1, c2) SELECT * FROM test2;
INSERT INTO test PARTITION(p1, p2) WITH LABEL `label1` SELECT * FROM test2;
INSERT INTO test WITH LABEL `label1` (c1, c2) SELECT * FROM test2;
INSERT INTO tbl1 SELECT * FROM empty_tbl;
INSERT INTO tbl1 SELECT * FROM tbl2;
INSERT INTO tbl1 WITH LABEL my_label1 SELECT * FROM tbl2;
INSERT INTO tbl1 SELECT * FROM tbl2 WHERE k1 = "a"
