SHOW TABLES;
SHOW TABLES LIKE '%cm%';
SHOW FULL TABLES;
SHOW CREATE TABLE demo.test_table;
SHOW BRIEF CREATE TABLE demo.test_table;
DESC test_table;
SHOW TABLE STATUS;
SHOW TABLE STATUS FROM db LIKE "%test%";
SHOW ALTER TABLE COLUMN;
SHOW ALTER TABLE COLUMN WHERE TableName = "table1" ORDER BY CreateTime DESC LIMIT 1;
SHOW ALTER TABLE ROLLUP FROM example_db;
SHOW FULL COLUMNS FROM t_agg;
SHOW COLUMNS FROM t_agg
