-- Oracle 19C+ CREATE SEQUENCE with all options

-- Customer reported issue
CREATE SEQUENCE owner.seq_name MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;

-- Basic sequence
CREATE SEQUENCE basic_seq START WITH 1 INCREMENT BY 1;

-- KEEP / NOKEEP (Oracle 12c+)
CREATE SEQUENCE keep_seq KEEP;
CREATE SEQUENCE nokeep_seq NOKEEP;

-- SCALE options (Oracle 18c+)
CREATE SEQUENCE scale_seq SCALE;
CREATE SEQUENCE scale_extend_seq SCALE EXTEND;
CREATE SEQUENCE scale_noextend_seq SCALE NOEXTEND;
CREATE SEQUENCE noscale_seq NOSCALE;

-- SHARD options (Oracle 12c Release 2+)
CREATE SEQUENCE shard_seq SHARD;
CREATE SEQUENCE shard_extend_seq SHARD EXTEND;
CREATE SEQUENCE shard_noextend_seq SHARD NOEXTEND;
CREATE SEQUENCE noshard_seq NOSHARD;

-- GLOBAL / SESSION (Oracle 18c+)
CREATE SEQUENCE global_seq GLOBAL;
CREATE SEQUENCE session_seq SESSION;

-- IF NOT EXISTS (Oracle 23c+)
CREATE SEQUENCE IF NOT EXISTS new_seq START WITH 1;

-- SHARING clause
CREATE SEQUENCE shared_meta_seq SHARING = METADATA;
CREATE SEQUENCE shared_data_seq SHARING = DATA;
CREATE SEQUENCE shared_none_seq SHARING = NONE;

-- Full example with all options
CREATE SEQUENCE full_seq
    START WITH 1000
    INCREMENT BY 10
    MINVALUE 1
    MAXVALUE 999999999
    CACHE 50
    ORDER
    NOCYCLE
    NOKEEP
    NOSCALE
    GLOBAL
    SHARING = METADATA;
